version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: galievdf-netology-prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - galievdf-my-netology-hw
    restart: always
  pushgateway:
    image: prom/pushgateway:latest
    container_name: galievdf-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - galievdf-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: galievdf-netology-alertmanager
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/data
    networks:
      - galievdf-my-netology-hw
    depends_on:
      - prometheus
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: galievdf-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - ./custom.ini:/etc/grafana/custom.ini
      - grafana-data:/var/lib/grafana
    networks:
      - galievdf-my-netology-hw
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:
networks:
  galievdf-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
